<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectType>Local</ProjectType>
    <AssemblyKeyContainerName>
    </AssemblyKeyContainerName>
    <AssemblyName>IBatisNet.Common</AssemblyName>
    <AssemblyOriginatorKeyFile>AssemblyKey.snk</AssemblyOriginatorKeyFile>
    <DefaultClientScript>JScript</DefaultClientScript>
    <DefaultHTMLPageLayout>Grid</DefaultHTMLPageLayout>
    <DefaultTargetSchema>IE50</DefaultTargetSchema>
    <DelaySign>false</DelaySign>
    <OutputType>Library</OutputType>
    <RootNamespace>IBatisNet.Common</RootNamespace>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <StartupObject>
    </StartupObject>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants>TRACE;DEBUG;dotnet2</DefineConstants>
    <DocumentationFile>IBatisNet.Common.xml</DocumentationFile>
    <FileAlignment>4096</FileAlignment>
    <NoStdLib>false</NoStdLib>
    <NoWarn>
    </NoWarn>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants>TRACE;dotnet2</DefineConstants>
    <DocumentationFile>IBatisNet.Common.xml</DocumentationFile>
    <FileAlignment>4096</FileAlignment>
    <NoStdLib>false</NoStdLib>
    <NoWarn>
    </NoWarn>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <DebugType>none</DebugType>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Transaction\**" />
    <EmbeddedResource Remove="Transaction\**" />
    <None Remove="Transaction\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Xml">
      <Name>System.XML</Name>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ChangeLog.txt" />
    <Content Include="licence.txt" />
    <Content Include="notice.txt" />
    <Content Include="provider.xsd">
      <SubType>
      </SubType>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.2.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 2.0 %28x86%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.0 %28x86%29</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Logging\IDataReaderProxy.cs" />
    <Compile Remove="Logging\IDbCommandProxy.cs" />
    <Compile Remove="Logging\IDbConnectionProxy.cs" />
    <Compile Remove="Utilities\Objects\Members\MemberAccessorFactory.cs" />
    <Compile Remove="Utilities\Proxy\CachedProxyGenerator.cs" />
    <Compile Remove="Utilities\Proxy\IProxyGenerator.cs" />
    <Compile Remove="Utilities\Proxy\ProxyGeneratorFactory.cs" />
  </ItemGroup>
  <PropertyGroup />
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Company>http://ibatis.apache.org/</Company>
    <Product>iBATIS.NET</Product>
    <Copyright>Copyright 2007,2005 The Apache Software Foundation</Copyright>
    <AssemblyTitle>iBATIS.Common</AssemblyTitle>
    <Description>Common object used by DataAccess and DataMapper component in iBATIS.Net</Description>
    <AssemblyVersion>1.6.2</AssemblyVersion>
  </PropertyGroup>
  <Target Name="AfterBuild">
    <CreateItem Include="$(MSBuildProjectDirectory)\..\MSBuild\*.*" exclude="$(MSBuildProjectDirectory)\..\MSBuild\README.txt">
      <Output TaskParameter="Include" ItemName="ExternalFilesToDelete" />
    </CreateItem>
    <Delete Files="@(ExternalFilesToDelete)" />
    <Copy SourceFiles="$(ProjectDir)$(OutputPath)$(AssemblyName).dll" DestinationFiles="$(MSBuildProjectDirectory)\..\MSBuild\$(AssemblyName).dll" />
    <Copy SourceFiles="$(ProjectDir)$(OutputPath)$(AssemblyName).xml" DestinationFiles="$(MSBuildProjectDirectory)\..\MSBuild\$(AssemblyName).xml" />
    <Copy SourceFiles="$(ProjectDir)$(OutputPath)$(AssemblyName).pdb" DestinationFiles="$(MSBuildProjectDirectory)\..\MSBuild\$(AssemblyName).pdb" Condition="Exists('$(ProjectDir)$(OutputPath)$(AssemblyName).pdb')" />
    <CreateItem Include="$(ProjectDir)..\External-Bin\Net\4.0\*.*">
      <Output TaskParameter="Include" ItemName="ExternalFilesToCopy" />
    </CreateItem>
    <Copy SourceFiles="@(ExternalFilesToCopy)" DestinationFolder="$(MSBuildProjectDirectory)\..\MSBuild" />
  </Target>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.1.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>
</Project>