<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectType>Local</ProjectType>
    <AssemblyKeyContainerName>
    </AssemblyKeyContainerName>
    <AssemblyName>IBatisNet.DataMapper</AssemblyName>
    <AssemblyOriginatorKeyFile>AssemblyKey.snk</AssemblyOriginatorKeyFile>
    <DefaultClientScript>JScript</DefaultClientScript>
    <DefaultHTMLPageLayout>Grid</DefaultHTMLPageLayout>
    <DefaultTargetSchema>IE50</DefaultTargetSchema>
    <DelaySign>false</DelaySign>
    <OutputType>Library</OutputType>
    <RootNamespace>IBatisNet.DataMapper</RootNamespace>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <StartupObject>
    </StartupObject>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants>TRACE;DEBUG;dotnet2 dotnet4</DefineConstants>
    <DocumentationFile>IBatisNet.DataMapper.xml</DocumentationFile>
    <FileAlignment>4096</FileAlignment>
    <NoStdLib>false</NoStdLib>
    <NoWarn>
    </NoWarn>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants>TRACE;dotnet2</DefineConstants>
    <DocumentationFile>IBatisNet.DataMapper.xml</DocumentationFile>
    <FileAlignment>4096</FileAlignment>
    <NoStdLib>false</NoStdLib>
    <NoWarn>
    </NoWarn>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <DebugType>none</DebugType>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="SessionStore\**" />
    <EmbeddedResource Remove="SessionStore\**" />
    <None Remove="SessionStore\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Castle.Core">
      <HintPath>..\External-Bin\Net\4.0\Castle.Core.dll</HintPath>
    </Reference>
    <Reference Update="System">
      <Name>System</Name>
    </Reference>
    <Reference Include="System.configuration" />
    <Reference Update="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Update="System.Data">
      <Name>System.Data</Name>
    </Reference>
    <Reference Include="System.ServiceModel">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Web">
      <Name>System.Web</Name>
    </Reference>
    <Reference Update="System.Xml">
      <Name>System.XML</Name>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ChangeLog.txt" />
    <Content Include="licence.txt" />
    <Content Include="notice.txt" />
    <Content Include="ReadMe.txt" />
    <EmbeddedResource Include="SqlMap.xsd">
      <SubType>
      </SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="SqlMapConfig.xsd">
      <SubType>
      </SubType>
    </EmbeddedResource>
    <None Update="SqlMapModule.xsd">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.2.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 2.0 %28x86%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.0 %28x86%29</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IBatisNet.Common\IBatisNet.Common.Net45.2012.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Commands\EmbedParamsPreparedCommand.cs" />
    <Compile Remove="Configuration\ResultMapping\IColumn.cs" />
    <Compile Remove="MappedStatements\ResultStrategy\BaseResultStrategy.cs" />
  </ItemGroup>
  <PropertyGroup />
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Company>http://ibatis.apache.org/</Company>
    <Product>iBATIS.NET</Product>
    <Copyright>Copyright 2007,2005 The Apache Software Foundation</Copyright>
    <AssemblyTitle>IBatisNet.DataMapper</AssemblyTitle>
    <Description>Map objects to your SQL statements or stored procedures.</Description>
    <AssemblyVersion>1.6.3</AssemblyVersion>
  </PropertyGroup>
  <Target Name="AfterBuild">
    <Copy SourceFiles="$(ProjectDir)$(OutputPath)$(AssemblyName).dll" DestinationFiles="$(MSBuildProjectDirectory)\..\MSBuild\$(AssemblyName).dll" />
    <Copy SourceFiles="$(ProjectDir)$(OutputPath)$(AssemblyName).xml" DestinationFiles="$(MSBuildProjectDirectory)\..\MSBuild\$(AssemblyName).xml" />
    <Copy SourceFiles="$(ProjectDir)$(OutputPath)$(AssemblyName).pdb" DestinationFiles="$(MSBuildProjectDirectory)\..\MSBuild\$(AssemblyName).pdb" Condition="Exists('$(ProjectDir)$(OutputPath)$(AssemblyName).pdb')" />
  </Target>
</Project>