<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Config\Definitions\Global.xml" />
      <EmbeddedResource Include="Config\Definitions\Holiday.xml" />
      <EmbeddedResource Include="Config\Providers.config" />
      <None Remove="Config\Definitions\CannedQuery.xml" />
      <EmbeddedResource Include="Config\Definitions\CannedQuery.xml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ORBatis.Common\ORBatis.Common.csproj" />
    </ItemGroup>

</Project>
