<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>IBatisNet.DataMapper</AssemblyName>
        <RootNamespace>IBatisNet.DataMapper</RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ORBatis.Common\ORBatis.Common.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Castle.Core" Version="5.2.1"/>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.7"/>
        <PackageReference Include="System.Security.Permissions" Version="9.0.7"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="SqlMap.xsd">
            <SubType>
            </SubType>
        </EmbeddedResource>
        <EmbeddedResource Include="SqlMapConfig.xsd">
            <SubType>
            </SubType>
        </EmbeddedResource>
    </ItemGroup>

</Project>
